# Generated by Django 4.2.6 on 2023-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=20)),
                ('dir_name', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=30)),
            ],
        ),
    ]
