# Generated by Django 4.2.6 on 2023-11-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
